<template>
  <main class="min-h-screen w-screen bg-secondary text-primary">
    <div class="grid w-full grid-cols-[30vw_30vw_30vw] gap-x-[2vw] px-[2vw] py-16">
      <section class="pb-8">
        <h2 class="uppercase text-3xl font-bold tracking-tight">
          Chi siamo
        </h2>
        <p class="mt-4 max-w-2xl text-lg leading-relaxed">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dictum felis dolor, venenatis mattis erat tincidunt condimentum. Proin posuere massa sed turpis viverra, ac elementum odio semper. Sed sed justo ornare elit interdum volutpat non sed ipsum. Duis efficitur iaculis metus sit amet iaculis. Nulla vulputate libero id felis lacinia egestas. Curabitur quis dignissim eros, vitae faucibus purus. Suspendisse venenatis at purus id sollicitudin. Suspendisse sit amet augue id nibh sagittis egestas sed malesuada lacus. Pellentesque eros dui, pulvinar quis nibh et, ullamcorper dictum eros. Ut eget elit quis nunc eleifend dictum ac quis dolor. Aliquam erat volutpat.<br><br>Aliquam nulla lacus, sollicitudin vulputate consequat ut, imperdiet quis erat. Donec quis dolor vel velit tempus consectetur at vel lacus. Duis sed tincidunt felis. Vestibulum nunc felis, condimentum id hendrerit eget, efficitur at diam. Sed condimentum enim at ligula mollis pulvinar. Suspendisse sit amet dolor malesuada, commodo dui in, iaculis mauris. Donec ultrices erat at eros commodo scelerisque. Cras velit erat, egestas ac nisi in, dapibus feugiat justo. Vestibulum quis accumsan nulla.<br><br>Praesent mi ligula, finibus placerat massa condimentum, consectetur dapibus libero. Morbi dignissim fermentum rutrum. Cras metus mauris, interdum sed porttitor quis, interdum non ipsum. Nullam semper vitae est non commodo. Nulla feugiat ex et augue lobortis, ac malesuada lacus maximus. Aenean dignissim venenatis tempus. Vestibulum lobortis imperdiet augue, non finibus nulla ornare nec. Donec eu maximus mauris, eu accumsan mauris. Suspendisse gravida ipsum ultrices, viverra orci ut, accumsan purus. Curabitur congue faucibus odio, ut euismod velit lacinia et. Fusce gravida elementum lectus, eget facilisis nisl dignissim et. Phasellus nec sapien tempus, ultricies neque quis, tincidunt lacus. Fusce odio lorem, hendrerit et arcu nec, placerat pretium magna.
        </p>
      </section>

      <section class="pb-8">
        <h2 class="uppercase text-3xl font-bold tracking-tight">
          Cosa facciamo
        </h2>
        <p class="mt-4 max-w-2xl text-lg leading-relaxed">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dictum felis dolor, venenatis mattis erat tincidunt condimentum. Proin posuere massa sed turpis viverra, ac elementum odio semper. Sed sed justo ornare elit interdum volutpat non sed ipsum. Duis efficitur iaculis metus sit amet iaculis. Nulla vulputate libero id felis lacinia egestas. Curabitur quis dignissim eros, vitae faucibus purus. Suspendisse venenatis at purus id sollicitudin. Suspendisse sit amet augue id nibh sagittis egestas sed malesuada lacus. Pellentesque eros dui, pulvinar quis nibh et, ullamcorper dictum eros. Ut eget elit quis nunc eleifend dictum ac quis dolor. Aliquam erat volutpat.<br><br>Aliquam nulla lacus, sollicitudin vulputate consequat ut, imperdiet quis erat. Donec quis dolor vel velit tempus consectetur at vel lacus. Duis sed tincidunt felis. Vestibulum nunc felis, condimentum id hendrerit eget, efficitur at diam. Sed condimentum enim at ligula mollis pulvinar. Suspendisse sit amet dolor malesuada, commodo dui in, iaculis mauris. Donec ultrices erat at eros commodo scelerisque. Cras velit erat, egestas ac nisi in, dapibus feugiat justo. Vestibulum quis accumsan nulla.<br><br>Praesent mi ligula, finibus placerat massa condimentum, consectetur dapibus libero. Morbi dignissim fermentum rutrum. Cras metus mauris, interdum sed porttitor quis, interdum non ipsum. Nullam semper vitae est non commodo. Nulla feugiat ex et augue lobortis, ac malesuada lacus maximus. Aenean dignissim venenatis tempus. Vestibulum lobortis imperdiet augue, non finibus nulla ornare nec. Donec eu maximus mauris, eu accumsan mauris. Suspendisse gravida ipsum ultrices, viverra orci ut, accumsan purus. Curabitur congue faucibus odio, ut euismod velit lacinia et. Fusce gravida elementum lectus, eget facilisis nisl dignissim et. Phasellus nec sapien tempus, ultricies neque quis, tincidunt lacus. Fusce odio lorem, hendrerit et arcu nec, placerat pretium magna.
        </p>
      </section>

      <section>
        <h2 class="uppercase text-3xl font-bold tracking-tight">
          Perché lo facciamo?
        </h2>
        <p class="mt-4 max-w-2xl text-lg leading-relaxed">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dictum felis dolor, venenatis mattis erat tincidunt condimentum. Proin posuere massa sed turpis viverra, ac elementum odio semper. Sed sed justo ornare elit interdum volutpat non sed ipsum. Duis efficitur iaculis metus sit amet iaculis. Nulla vulputate libero id felis lacinia egestas. Curabitur quis dignissim eros, vitae faucibus purus. Suspendisse venenatis at purus id sollicitudin. Suspendisse sit amet augue id nibh sagittis egestas sed malesuada lacus. Pellentesque eros dui, pulvinar quis nibh et, ullamcorper dictum eros. Ut eget elit quis nunc eleifend dictum ac quis dolor. Aliquam erat volutpat.<br><br>Aliquam nulla lacus, sollicitudin vulputate consequat ut, imperdiet quis erat. Donec quis dolor vel velit tempus consectetur at vel lacus. Duis sed tincidunt felis. Vestibulum nunc felis, condimentum id hendrerit eget, efficitur at diam. Sed condimentum enim at ligula mollis pulvinar. Suspendisse sit amet dolor malesuada, commodo dui in, iaculis mauris. Donec ultrices erat at eros commodo scelerisque. Cras velit erat, egestas ac nisi in, dapibus feugiat justo. Vestibulum quis accumsan nulla.<br><br>Praesent mi ligula, finibus placerat massa condimentum, consectetur dapibus libero. Morbi dignissim fermentum rutrum. Cras metus mauris, interdum sed porttitor quis, interdum non ipsum. Nullam semper vitae est non commodo. Nulla feugiat ex et augue lobortis, ac malesuada lacus maximus. Aenean dignissim venenatis tempus. Vestibulum lobortis imperdiet augue, non finibus nulla ornare nec. Donec eu maximus mauris, eu accumsan mauris. Suspendisse gravida ipsum ultrices, viverra orci ut, accumsan purus. Curabitur congue faucibus odio, ut euismod velit lacinia et. Fusce gravida elementum lectus, eget facilisis nisl dignissim et. Phasellus nec sapien tempus, ultricies neque quis, tincidunt lacus. Fusce odio lorem, hendrerit et arcu nec, placerat pretium magna.
        </p>
      </section>
    </div>
  </main>
</template>